-- H2 + StdJDBCDelegate 会将布尔列写成 FALSE/TRUE，VARCHAR(1) 不足；扩宽后开发与 MySQL 均兼容

ALTER TABLE QRTZ_JOB_DETAILS ALTER COLUMN is_durable VARCHAR(12) NOT NULL;
ALTER TABLE QRTZ_JOB_DETAILS ALTER COLUMN is_nonconcurrent VARCHAR(12) NOT NULL;
ALTER TABLE QRTZ_JOB_DETAILS ALTER COLUMN is_update_data VARCHAR(12) NOT NULL;
ALTER TABLE QRTZ_JOB_DETAILS ALTER COLUMN requests_recovery VARCHAR(12) NOT NULL;

ALTER TABLE QRTZ_FIRED_TRIGGERS ALTER COLUMN is_nonconcurrent VARCHAR(12);
ALTER TABLE QRTZ_FIRED_TRIGGERS ALTER COLUMN requests_recovery VARCHAR(12);
