spring:
  data:
    redis:
      host: 192.168.50.105
      database: 7

  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.105:3406/quickboot-dev?characterEncoding=utf8&useUnicode=true&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: rootroot
