-- Database export: quickboot
-- Date: 2026-08-11 22:26:10
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `chat2bi_table_meta` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `db_source_type` varchar(32) NOT NULL COMMENT '数据源来源表标识, �? db_source / api_source / file_source / system_source',
  `db_source_id` varchar(32) NOT NULL COMMENT '对应来源表的主键ID',
  `schema_name` varchar(128) DEFAULT NULL COMMENT 'Schema�?,
  `table_name` varchar(128) NOT NULL COMMENT '表名',
  `source_comment` varchar(512) DEFAULT NULL COMMENT '表注�?�?同步写入, 每次同步覆盖)',
  `table_comment` varchar(512) DEFAULT NULL COMMENT '表注�?用户(用户手动填写, 同步不覆�?',
  `columns_json` text NOT NULL COMMENT '列定义[{name,type,source_comment,comment,is_primary,sample_values,nulltable}]',
  `relations_json` text DEFAULT NULL COMMENT '关联关系[{column,ref_table,ref_column,type}]',
  `is_enabled` tinyint(4) NOT NULL DEFAULT 1 COMMENT '对LLM可见: 0=�?1=�?,
  `synced_time` datetime DEFAULT NULL COMMENT '最近同步时�?,
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `tenant_id` int(11) DEFAULT NULL COMMENT '多租户标�?,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_table` (`db_source_type`,`db_source_id`,`schema_name`,`table_name`),
  KEY `idx_source` (`db_source_type`,`db_source_id`),
  KEY `idx_table_name` (`table_name`),
  KEY `idx_table_name_comment` (`table_name`,`source_comment`(100),`table_comment`(100)),
  KEY `idx_table_comment` (`table_comment`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `flyway_schema_history` (
  `installed_rank` int(11) NOT NULL,
  `version` varchar(50) DEFAULT NULL,
  `description` varchar(200) NOT NULL,
  `type` varchar(20) NOT NULL,
  `script` varchar(1000) NOT NULL,
  `checksum` int(11) DEFAULT NULL,
  `installed_by` varchar(100) NOT NULL,
  `installed_on` timestamp NOT NULL DEFAULT current_timestamp(),
  `execution_time` int(11) NOT NULL,
  `success` tinyint(1) NOT NULL,
  PRIMARY KEY (`installed_rank`),
  KEY `flyway_schema_history_s_idx` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `gen_table` (
  `table_id` bigint(20) NOT NULL,
  `table_name` varchar(200) NOT NULL,
  `table_comment` varchar(500) DEFAULT NULL,
  `sub_table_name` varchar(64) DEFAULT NULL,
  `sub_table_fk_name` varchar(64) DEFAULT NULL,
  `class_name` varchar(100) DEFAULT NULL,
  `tpl_category` varchar(200) DEFAULT 'crud',
  `tpl_web_type` varchar(30) DEFAULT 'element-plus',
  `package_name` varchar(100) DEFAULT NULL,
  `module_name` varchar(30) DEFAULT NULL,
  `business_name` varchar(30) DEFAULT NULL,
  `function_name` varchar(50) DEFAULT NULL,
  `function_author` varchar(50) DEFAULT NULL,
  `gen_type` char(1) DEFAULT '0',
  `gen_path` varchar(200) DEFAULT NULL,
  `parent_menu_id` bigint(20) DEFAULT NULL,
  `tree_code` varchar(64) DEFAULT NULL,
  `tree_parent_code` varchar(64) DEFAULT NULL,
  `tree_name` varchar(64) DEFAULT NULL,
  `options` varchar(1000) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`table_id`),
  UNIQUE KEY `uk_gen_table_table_name` (`table_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `gen_table_column` (
  `column_id` bigint(20) NOT NULL,
  `table_id` bigint(20) NOT NULL,
  `column_name` varchar(200) DEFAULT NULL,
  `column_comment` varchar(500) DEFAULT NULL,
  `column_type` varchar(100) DEFAULT NULL,
  `java_type` varchar(500) DEFAULT NULL,
  `java_field` varchar(200) DEFAULT NULL,
  `is_pk` char(1) DEFAULT NULL,
  `is_increment` char(1) DEFAULT NULL,
  `is_required` char(1) DEFAULT NULL,
  `is_insert` char(1) DEFAULT NULL,
  `is_edit` char(1) DEFAULT NULL,
  `is_list` char(1) DEFAULT NULL,
  `is_query` char(1) DEFAULT NULL,
  `query_type` varchar(200) DEFAULT NULL,
  `html_type` varchar(200) DEFAULT NULL,
  `dict_type` varchar(200) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`column_id`),
  KEY `idx_gen_table_column_table_id` (`table_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_age` (
  `id` varchar(36) NOT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `value` varchar(20) DEFAULT NULL COMMENT '�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_fengongsi` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `value` varchar(20) DEFAULT NULL COMMENT '�?,
  `type` varchar(32) DEFAULT NULL COMMENT '类型',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_huoyuedu` (
  `id` varchar(36) NOT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `value` varchar(20) DEFAULT NULL COMMENT '�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_sex` (
  `id` varchar(36) NOT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '性别',
  `value` varchar(20) DEFAULT NULL COMMENT '�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_work` (
  `id` varchar(36) NOT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `value` varchar(20) DEFAULT NULL COMMENT '�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_wxtl` (
  `id` varchar(36) NOT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `value` varchar(20) DEFAULT NULL COMMENT '�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_wxtlshuliang` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `value` int(10) DEFAULT NULL COMMENT '�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huiyuan_xueli` (
  `id` varchar(36) NOT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `value` varchar(20) DEFAULT NULL COMMENT '�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_dict` (
  `id` varchar(32) NOT NULL,
  `dict_name` varchar(100) DEFAULT NULL COMMENT '字典名称',
  `dict_code` varchar(100) DEFAULT NULL COMMENT '字典编码',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `del_flag` int(1) DEFAULT NULL COMMENT '删除状�?,
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `type` int(1) DEFAULT 0 COMMENT '字典类型0为string,1为number',
  `tenant_id` varchar(10) DEFAULT NULL COMMENT '多租户标�?,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sd_dict_code` (`dict_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_dict_item` (
  `id` varchar(32) NOT NULL,
  `dict_id` varchar(32) DEFAULT NULL COMMENT '字典id',
  `item_text` varchar(100) DEFAULT NULL COMMENT '字典项文�?,
  `item_value` varchar(100) DEFAULT NULL COMMENT '字典项�?,
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `sort_order` int(10) DEFAULT NULL COMMENT '排序',
  `status` int(11) DEFAULT NULL COMMENT '状态（1启用 0不启用）',
  `create_by` varchar(32) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(32) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sdi_role_dict_id` (`dict_id`),
  KEY `idx_sdi_role_sort_order` (`sort_order`),
  KEY `idx_sdi_status` (`status`),
  KEY `idx_sdi_dict_val` (`dict_id`,`item_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `code` varchar(50) DEFAULT NULL COMMENT '编码',
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `note` varchar(255) DEFAULT NULL COMMENT '说明',
  `status` varchar(10) DEFAULT NULL COMMENT '状�?,
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `json_str` longtext DEFAULT NULL COMMENT 'json字符�?,
  `api_url` varchar(255) DEFAULT NULL COMMENT '请求地址',
  `thumb` text DEFAULT NULL COMMENT '缩略�?,
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '修改�?,
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识0-正常,1-已删�?,
  `api_method` varchar(255) DEFAULT NULL COMMENT '请求方法0-get,1-post',
  `api_code` varchar(255) DEFAULT NULL COMMENT '请求编码',
  `template` tinyint(1) DEFAULT NULL COMMENT '是否是模�?0-�?1-不是',
  `view_count` bigint(15) DEFAULT 0 COMMENT '浏览次数',
  `css_str` text DEFAULT NULL COMMENT 'css增强',
  `js_str` text DEFAULT NULL COMMENT 'js增强',
  `py_str` text DEFAULT NULL COMMENT 'py增强',
  `tenant_id` varchar(10) DEFAULT NULL COMMENT '多租户标�?,
  `update_count` int(11) DEFAULT 0 COMMENT '乐观锁版�?,
  `submit_form` tinyint(1) DEFAULT NULL COMMENT '是否填报报表 0不是,1�?,
  `is_multi_sheet` tinyint(4) DEFAULT NULL COMMENT '是否多sheet报表 1�?0�?,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_jmreport_code` (`code`),
  KEY `uniq_jmreport_createby` (`create_by`),
  KEY `uniq_jmreport_delflag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_category` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `name` varchar(100) NOT NULL COMMENT '分类名称',
  `parent_id` varchar(32) DEFAULT NULL COMMENT '父级id',
  `iz_leaf` int(1) DEFAULT NULL COMMENT '是否为叶子节�?0 �?1�?',
  `source_type` varchar(10) DEFAULT NULL COMMENT '来源类型( report 积木报表 screen 大屏  drag 仪表�?',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新�?,
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `tenant_id` varchar(11) DEFAULT NULL COMMENT '租户id',
  `del_flag` int(1) DEFAULT NULL COMMENT '删除状�?0未删除，1已删除，2临时删除)',
  `sort_no` int(11) DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_data_source` (
  `id` varchar(36) NOT NULL,
  `name` varchar(100) DEFAULT NULL COMMENT '数据源名�?,
  `report_id` varchar(100) DEFAULT NULL COMMENT '报表_id',
  `code` varchar(100) DEFAULT NULL COMMENT '编码',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `db_type` varchar(10) DEFAULT NULL COMMENT '数据库类�?,
  `db_driver` varchar(100) DEFAULT NULL COMMENT '驱动�?,
  `db_url` varchar(500) DEFAULT NULL COMMENT '数据源地址',
  `db_username` varchar(100) DEFAULT NULL COMMENT '用户�?,
  `db_password` varchar(100) DEFAULT NULL COMMENT '密码',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  `connect_times` int(11) DEFAULT 0 COMMENT '连接失败次数',
  `tenant_id` varchar(10) DEFAULT NULL COMMENT '多租户标�?,
  `type` varchar(10) DEFAULT NULL COMMENT '类型(report:报表;drag:仪表�?',
  PRIMARY KEY (`id`),
  KEY `idx_jmdatasource_report_id` (`report_id`),
  KEY `idx_jmdatasource_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_db` (
  `id` varchar(36) NOT NULL COMMENT 'id',
  `jimu_report_id` varchar(32) DEFAULT NULL COMMENT '主键字段',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  `db_code` varchar(32) DEFAULT NULL COMMENT '数据集编�?,
  `db_ch_name` varchar(50) DEFAULT NULL COMMENT '数据集名�?,
  `db_type` varchar(32) DEFAULT NULL COMMENT '数据源类�?,
  `db_table_name` varchar(32) DEFAULT NULL COMMENT '数据库表�?,
  `db_dyn_sql` longtext DEFAULT NULL COMMENT '动态查询SQL',
  `db_key` varchar(32) DEFAULT NULL COMMENT '数据源KEY',
  `tb_db_key` varchar(32) DEFAULT NULL COMMENT '填报数据�?,
  `tb_db_table_name` varchar(32) DEFAULT NULL COMMENT '填报数据�?,
  `java_type` varchar(32) DEFAULT NULL COMMENT 'java类数据集  类型（spring:springkey,class:java类名�?,
  `java_value` varchar(255) DEFAULT NULL COMMENT 'java类数据源  数值（bean key/java类名�?,
  `api_url` varchar(255) DEFAULT NULL COMMENT '请求地址',
  `api_method` varchar(255) DEFAULT NULL COMMENT '请求方法0-get,1-post',
  `is_list` varchar(10) DEFAULT '0' COMMENT '是否是列�?�?�?默认0',
  `is_page` varchar(10) DEFAULT NULL COMMENT '是否作为分页,0:不分页，1:分页',
  `db_source` varchar(255) DEFAULT NULL COMMENT '数据�?,
  `db_source_type` varchar(50) DEFAULT NULL COMMENT '数据库类�?MYSQL ORACLE SQLSERVER',
  `json_data` text DEFAULT NULL COMMENT 'json数据，直接解析json内容',
  `api_convert` varchar(255) DEFAULT NULL COMMENT 'api转换�?,
  `iz_shared_source` int(1) DEFAULT NULL COMMENT '是否为共享数据源(0 �?1 �?',
  `jimu_shared_source_id` varchar(32) DEFAULT NULL COMMENT '指向共享数据集的id',
  PRIMARY KEY (`id`),
  KEY `idx_jmreportdb_db_key` (`db_key`),
  KEY `idx_jimu_report_id` (`jimu_report_id`),
  KEY `idx_db_source_id` (`db_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_db_field` (
  `id` varchar(36) NOT NULL COMMENT 'id',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  `jimu_report_db_id` varchar(32) DEFAULT NULL COMMENT '数据源ID',
  `field_name` varchar(80) DEFAULT NULL COMMENT '字段�?,
  `field_name_physics` varchar(200) DEFAULT NULL COMMENT '物理字段名（文件数据集使用，存的是excel的字段标题）',
  `field_text` varchar(50) DEFAULT NULL COMMENT '字段文本',
  `widget_type` varchar(50) DEFAULT NULL COMMENT '控件类型',
  `widget_width` int(10) DEFAULT NULL COMMENT '控件宽度',
  `order_num` int(3) DEFAULT NULL COMMENT '排序',
  `search_flag` int(3) DEFAULT 0 COMMENT '查询标识0�?�?默认0',
  `search_mode` int(3) DEFAULT NULL COMMENT '查询模式1简�?范围',
  `dict_code` varchar(255) DEFAULT NULL COMMENT '字典编码支持从表中取数据',
  `search_value` varchar(100) DEFAULT NULL COMMENT '查询默认�?,
  `search_format` varchar(50) DEFAULT NULL COMMENT '查询时间格式化表达式',
  `ext_json` text DEFAULT NULL COMMENT '参数配置',
  PRIMARY KEY (`id`),
  KEY `idx_jrdf_jimu_report_db_id` (`jimu_report_db_id`),
  KEY `idx_dbfield_order_num` (`order_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_db_param` (
  `id` varchar(36) NOT NULL,
  `jimu_report_head_id` varchar(36) NOT NULL COMMENT '动态报表ID',
  `param_name` varchar(32) NOT NULL COMMENT '参数字段',
  `param_txt` varchar(32) DEFAULT NULL COMMENT '参数文本',
  `param_value` varchar(1000) DEFAULT NULL COMMENT '参数默认�?,
  `order_num` int(11) DEFAULT NULL COMMENT '排序',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  `search_flag` int(1) DEFAULT NULL COMMENT '查询标识0�?�?默认0',
  `widget_type` varchar(50) DEFAULT NULL COMMENT '查询控件类型',
  `search_mode` int(1) DEFAULT NULL COMMENT '查询模式1简�?范围',
  `dict_code` varchar(255) DEFAULT NULL COMMENT '字典',
  `search_format` varchar(50) DEFAULT NULL COMMENT '查询时间格式化表达式',
  `ext_json` text DEFAULT NULL COMMENT '参数配置',
  PRIMARY KEY (`id`),
  KEY `idx_jrdp_jimu_report_head_id` (`jimu_report_head_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_export_job` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `name` varchar(100) DEFAULT NULL COMMENT '任务名称',
  `begin_time` datetime DEFAULT NULL COMMENT '开始时�?,
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `exec_interval` varchar(100) DEFAULT NULL COMMENT '执行频率',
  `report_conf` text DEFAULT NULL COMMENT '导出报表配置',
  `last_run_time` datetime DEFAULT NULL COMMENT '最后执行时�?,
  `receiver_email` text DEFAULT NULL COMMENT '接收通知的邮�?,
  `file_sync_path` varchar(255) DEFAULT NULL COMMENT '文件同步路径',
  `status` int(11) DEFAULT NULL COMMENT '状�?0:停止;1:启动)',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '修改�?,
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `tenant_id` varchar(10) DEFAULT NULL COMMENT '多租户标�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_export_log` (
  `id` varchar(32) NOT NULL,
  `batch_no` varchar(50) DEFAULT NULL COMMENT '批次编号',
  `export_channel` varchar(20) DEFAULT NULL COMMENT '导出渠道',
  `export_from` varchar(20) DEFAULT NULL COMMENT '发起来源',
  `from_id` varchar(32) DEFAULT NULL COMMENT '来源id',
  `export_type` varchar(10) DEFAULT NULL COMMENT '导出类型',
  `report_id` text DEFAULT NULL COMMENT '报表id',
  `download_path` varchar(255) DEFAULT NULL COMMENT '下载路径',
  `status` varchar(15) DEFAULT NULL COMMENT '状�?,
  `err_msg` text DEFAULT NULL COMMENT '错误消息',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `tenant_id` varchar(10) DEFAULT NULL COMMENT '多租户标�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_ext_data` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `biz_type` varchar(100) NOT NULL COMMENT '业务类型标识，如 report_share、temp_config �?,
  `name` varchar(200) DEFAULT NULL COMMENT '名称，展示用',
  `descr` varchar(500) DEFAULT NULL COMMENT '描述信息',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签，多个用逗号分隔',
  `data_value` longtext DEFAULT NULL COMMENT '实际存储内容',
  `metadata` varchar(500) DEFAULT NULL COMMENT '元数据，用于存储补充信息',
  `status` tinyint(4) DEFAULT 1 COMMENT '状态标识：1正常 0禁用',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT current_timestamp() COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '修改�?,
  `update_time` datetime DEFAULT current_timestamp() COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_biz` (`biz_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_icon_lib` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `name` varchar(100) DEFAULT NULL COMMENT '图片名称',
  `type` varchar(32) DEFAULT NULL COMMENT '图片类型',
  `image_url` varchar(255) DEFAULT NULL COMMENT '图片地址',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_link` (
  `id` varchar(32) NOT NULL COMMENT '主键id',
  `report_id` varchar(32) DEFAULT NULL COMMENT '积木设计器id',
  `parameter` text DEFAULT NULL COMMENT '参数',
  `eject_type` varchar(1) DEFAULT NULL COMMENT '弹出方式�? 当前页面 1 新窗口）',
  `link_name` varchar(255) DEFAULT NULL COMMENT '链接名称',
  `api_method` varchar(1) DEFAULT NULL COMMENT '请求方法0-get,1-post',
  `link_type` varchar(1) DEFAULT NULL COMMENT '链接方式(0 网络报表 1 网络连接 2 图表联动)',
  `api_url` varchar(1000) DEFAULT NULL COMMENT '外网api',
  `link_chart_id` varchar(50) DEFAULT NULL COMMENT '联动图表的ID',
  `expression` varchar(255) DEFAULT NULL COMMENT '表达�?,
  `requirement` varchar(255) DEFAULT NULL COMMENT '条件',
  PRIMARY KEY (`id`),
  KEY `uniq_link_reportid` (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_map` (
  `id` varchar(64) NOT NULL COMMENT '主键',
  `label` varchar(125) DEFAULT NULL COMMENT '地图名称',
  `name` varchar(125) DEFAULT NULL COMMENT '地图编码',
  `data` longtext DEFAULT NULL COMMENT '地图数据',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改�?,
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `del_flag` varchar(1) DEFAULT NULL COMMENT '0表示未删�?1表示删除',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部�?,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_jmreport_map_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_share` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `report_id` varchar(32) DEFAULT NULL COMMENT '在线excel设计器id',
  `preview_url` varchar(1000) DEFAULT NULL COMMENT '预览地址',
  `preview_lock` varchar(4) DEFAULT NULL COMMENT '密码�?,
  `last_update_time` datetime DEFAULT NULL COMMENT '最后更新时�?,
  `term_of_validity` varchar(1) DEFAULT NULL COMMENT '有效�?0:永久有效�?:1天，2:7�?',
  `status` varchar(1) DEFAULT NULL COMMENT '是否过期(0未过期，1已过�?',
  `preview_lock_status` varchar(1) DEFAULT NULL COMMENT '密码锁状�?0不存在密码锁�?存在密码�?',
  `share_token` varchar(50) DEFAULT NULL COMMENT '分享token',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_report_id` (`report_id`),
  KEY `idx_jrs_share_token` (`share_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jimu_report_sheet` (
  `id` varchar(64) NOT NULL COMMENT '主键（Sheet ID�?,
  `report_id` varchar(64) NOT NULL COMMENT '报表ID',
  `sheet_name` varchar(255) NOT NULL COMMENT 'Sheet名称',
  `sheet_order` int(11) NOT NULL COMMENT '排序（可以为负数，负数表示在默认sheet前面�?,
  `json_str` longtext DEFAULT NULL COMMENT '该sheet的完整jsonStr',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建�?,
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新�?,
  PRIMARY KEY (`id`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_sheet_order` (`report_id`,`sheet_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_comp` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `parent_id` varchar(32) DEFAULT NULL,
  `comp_name` varchar(50) DEFAULT NULL COMMENT '组件名称',
  `comp_type` varchar(20) DEFAULT NULL,
  `icon` varchar(50) DEFAULT NULL COMMENT '图标',
  `order_num` int(11) DEFAULT NULL COMMENT '排序',
  `type_id` int(11) DEFAULT NULL COMMENT '组件类型',
  `comp_config` longtext DEFAULT NULL COMMENT '组件配置',
  `status` varchar(2) DEFAULT '0' COMMENT '状�?:无效 1:有效',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_dataset_head` (
  `id` varchar(32) NOT NULL COMMENT 'id',
  `name` varchar(100) NOT NULL COMMENT '名称',
  `code` varchar(36) DEFAULT NULL COMMENT '编码',
  `parent_id` varchar(36) DEFAULT NULL COMMENT '父id',
  `db_source` varchar(100) DEFAULT NULL COMMENT '动态数据源',
  `query_sql` varchar(5000) DEFAULT '0' COMMENT '查询数据SQL',
  `content` varchar(1000) DEFAULT NULL COMMENT '描述',
  `iz_agent` varchar(10) DEFAULT '0' COMMENT 'iz_agent',
  `data_type` varchar(50) DEFAULT NULL COMMENT '数据类型',
  `api_method` varchar(10) DEFAULT NULL COMMENT 'api方法：get/post',
  `create_time` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `low_app_id` varchar(32) DEFAULT NULL COMMENT '应用ID',
  `tenant_id` int(10) DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_dataset_item` (
  `id` varchar(32) NOT NULL COMMENT 'id',
  `head_id` varchar(36) NOT NULL COMMENT '主表ID',
  `field_name` varchar(36) DEFAULT NULL COMMENT '字段�?,
  `field_txt` varchar(1000) DEFAULT NULL COMMENT '字段文本',
  `field_type` varchar(10) DEFAULT NULL COMMENT '字段类型',
  `widget_type` varchar(30) DEFAULT NULL COMMENT '控件类型',
  `dict_code` varchar(500) DEFAULT NULL COMMENT '字典Code',
  `dict_table` varchar(125) DEFAULT NULL,
  `dict_text` varchar(125) DEFAULT NULL,
  `iz_show` varchar(5) DEFAULT NULL COMMENT '是否列表显示',
  `iz_search` varchar(10) DEFAULT NULL COMMENT '是否查询',
  `iz_total` varchar(5) DEFAULT NULL COMMENT '是否计算总计（仅对数值有效）',
  `search_mode` varchar(10) DEFAULT NULL COMMENT '查询模式',
  `order_num` int(11) DEFAULT NULL COMMENT '排序',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改�?,
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_oddi_head_id` (`head_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_dataset_param` (
  `id` varchar(36) NOT NULL,
  `head_id` varchar(36) NOT NULL COMMENT '动态报表ID',
  `param_name` varchar(32) NOT NULL COMMENT '参数字段',
  `param_txt` varchar(32) DEFAULT NULL COMMENT '参数文本',
  `param_value` varchar(1000) DEFAULT NULL COMMENT '参数默认�?,
  `order_num` int(11) DEFAULT NULL COMMENT '排序',
  `iz_search` int(11) DEFAULT NULL COMMENT '查询标识0�?�?默认0',
  `widget_type` varchar(50) DEFAULT NULL COMMENT '查询控件类型',
  `search_mode` int(11) DEFAULT NULL COMMENT '查询模式1简�?范围',
  `dict_code` varchar(255) DEFAULT NULL COMMENT '字典',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  PRIMARY KEY (`id`),
  KEY `idx_oddp_head_id` (`head_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_page` (
  `id` varchar(50) NOT NULL COMMENT '主键',
  `name` varchar(100) DEFAULT NULL COMMENT '界面名称',
  `path` varchar(100) DEFAULT NULL COMMENT '访问路径',
  `background_color` varchar(10) DEFAULT NULL COMMENT '背景�?,
  `background_image` varchar(255) DEFAULT NULL COMMENT '背景�?,
  `design_type` int(1) DEFAULT NULL COMMENT '设计模式(1:pc,2:手机,3:平板)',
  `theme` varchar(10) DEFAULT NULL COMMENT '主题�?,
  `style` varchar(20) DEFAULT NULL COMMENT '面板主题',
  `cover_url` varchar(500) DEFAULT NULL COMMENT '封面�?,
  `des_json` varchar(1000) DEFAULT NULL COMMENT '仪表盘主配置JSON',
  `template` longtext DEFAULT NULL COMMENT '布局json',
  `protection_code` varchar(32) DEFAULT NULL COMMENT '保护�?,
  `type` varchar(64) DEFAULT NULL COMMENT '文件夹类',
  `iz_template` varchar(10) DEFAULT '0' COMMENT '是否模板(1:是；0不是)',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  `low_app_id` varchar(50) DEFAULT NULL COMMENT '应用ID',
  `tenant_id` int(10) DEFAULT NULL COMMENT '租户ID',
  `update_count` int(10) DEFAULT 1,
  `visits_num` int(11) DEFAULT NULL COMMENT '访问次数',
  `del_flag` int(11) DEFAULT NULL COMMENT '删除状�? 0未删�?1已删�?',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_page_comp` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `parent_id` varchar(32) DEFAULT NULL COMMENT '父组件ID',
  `page_Id` varchar(50) DEFAULT NULL COMMENT '界面ID',
  `comp_id` varchar(32) DEFAULT NULL COMMENT '组件库ID',
  `component` varchar(50) DEFAULT NULL COMMENT '组件名称',
  `config` longtext DEFAULT NULL COMMENT '组件配置',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_share` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `drag_id` varchar(32) DEFAULT NULL COMMENT '在线仪表盘设计器id',
  `preview_url` varchar(1000) DEFAULT NULL COMMENT '预览地址',
  `preview_lock` varchar(4) DEFAULT NULL COMMENT '密码�?,
  `last_update_time` datetime DEFAULT NULL COMMENT '最后更新时�?,
  `term_of_validity` varchar(1) DEFAULT NULL COMMENT '有效�?0:永久有效�?:1天，7:7�?',
  `status` varchar(1) DEFAULT NULL COMMENT '是否过期(0未过期，1已过�?',
  `preview_lock_status` varchar(1) DEFAULT NULL COMMENT '是否为密码锁(0 �?1�?',
  `share_token` varchar(32) DEFAULT NULL COMMENT '分享token',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ods_drag_id` (`drag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `onl_drag_table_relation` (
  `id` varchar(50) NOT NULL COMMENT '主键',
  `aggregation_name` varchar(100) DEFAULT NULL COMMENT '聚合表名�?,
  `aggregation_desc` varchar(100) DEFAULT NULL COMMENT '聚合表描�?,
  `relation_forms` longtext DEFAULT NULL COMMENT '关联表单',
  `filter_condition` longtext DEFAULT NULL COMMENT '过滤条件',
  `header_fields` longtext DEFAULT NULL COMMENT '表头字段',
  `calculate_fields` longtext DEFAULT NULL COMMENT '公式字段',
  `validate_info` longtext DEFAULT NULL COMMENT '校验信息',
  `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除状�?0-正常,1-已删�?',
  `low_app_id` varchar(50) DEFAULT NULL COMMENT '应用ID',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人登录名�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人登录名�?,
  `update_time` datetime DEFAULT NULL COMMENT '更新日期',
  PRIMARY KEY (`id`),
  KEY `idx_aggregation_name` (`aggregation_name`),
  KEY `idx_del_flag` (`del_flag`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_create_by` (`create_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_blob_triggers` (
  `sched_name` varchar(120) NOT NULL,
  `trigger_name` varchar(200) NOT NULL,
  `trigger_group` varchar(200) NOT NULL,
  `blob_data` blob DEFAULT NULL,
  PRIMARY KEY (`sched_name`,`trigger_name`,`trigger_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_calendars` (
  `sched_name` varchar(120) NOT NULL,
  `calendar_name` varchar(200) NOT NULL,
  `calendar` blob NOT NULL,
  PRIMARY KEY (`sched_name`,`calendar_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_cron_triggers` (
  `sched_name` varchar(120) NOT NULL,
  `trigger_name` varchar(200) NOT NULL,
  `trigger_group` varchar(200) NOT NULL,
  `cron_expression` varchar(200) NOT NULL,
  `time_zone_id` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`sched_name`,`trigger_name`,`trigger_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_fired_triggers` (
  `sched_name` varchar(120) NOT NULL,
  `entry_id` varchar(95) NOT NULL,
  `trigger_name` varchar(200) NOT NULL,
  `trigger_group` varchar(200) NOT NULL,
  `instance_name` varchar(200) NOT NULL,
  `fired_time` bigint(20) NOT NULL,
  `sched_time` bigint(20) NOT NULL,
  `priority` int(11) NOT NULL,
  `state` varchar(16) NOT NULL,
  `job_name` varchar(200) DEFAULT NULL,
  `job_group` varchar(200) DEFAULT NULL,
  `is_nonconcurrent` varchar(12) DEFAULT NULL,
  `requests_recovery` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`sched_name`,`entry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_job_details` (
  `sched_name` varchar(120) NOT NULL,
  `job_name` varchar(200) NOT NULL,
  `job_group` varchar(200) NOT NULL,
  `description` varchar(250) DEFAULT NULL,
  `job_class_name` varchar(250) NOT NULL,
  `is_durable` varchar(12) NOT NULL,
  `is_nonconcurrent` varchar(12) NOT NULL,
  `is_update_data` varchar(12) NOT NULL,
  `requests_recovery` varchar(12) NOT NULL,
  `job_data` blob DEFAULT NULL,
  PRIMARY KEY (`sched_name`,`job_name`,`job_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_locks` (
  `sched_name` varchar(120) NOT NULL,
  `lock_name` varchar(40) NOT NULL,
  PRIMARY KEY (`sched_name`,`lock_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_paused_trigger_grps` (
  `sched_name` varchar(120) NOT NULL,
  `trigger_group` varchar(200) NOT NULL,
  PRIMARY KEY (`sched_name`,`trigger_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_scheduler_state` (
  `sched_name` varchar(120) NOT NULL,
  `instance_name` varchar(200) NOT NULL,
  `last_checkin_time` bigint(20) NOT NULL,
  `checkin_interval` bigint(20) NOT NULL,
  PRIMARY KEY (`sched_name`,`instance_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_simple_triggers` (
  `sched_name` varchar(120) NOT NULL,
  `trigger_name` varchar(200) NOT NULL,
  `trigger_group` varchar(200) NOT NULL,
  `repeat_count` bigint(20) NOT NULL,
  `repeat_interval` bigint(20) NOT NULL,
  `times_triggered` bigint(20) NOT NULL,
  PRIMARY KEY (`sched_name`,`trigger_name`,`trigger_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_simprop_triggers` (
  `sched_name` varchar(120) NOT NULL,
  `trigger_name` varchar(200) NOT NULL,
  `trigger_group` varchar(200) NOT NULL,
  `str_prop_1` varchar(512) DEFAULT NULL,
  `str_prop_2` varchar(512) DEFAULT NULL,
  `str_prop_3` varchar(512) DEFAULT NULL,
  `int_prop_1` int(11) DEFAULT NULL,
  `int_prop_2` int(11) DEFAULT NULL,
  `long_prop_1` bigint(20) DEFAULT NULL,
  `long_prop_2` bigint(20) DEFAULT NULL,
  `dec_prop_1` decimal(13,4) DEFAULT NULL,
  `dec_prop_2` decimal(13,4) DEFAULT NULL,
  `bool_prop_1` varchar(1) DEFAULT NULL,
  `bool_prop_2` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`sched_name`,`trigger_name`,`trigger_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrtz_triggers` (
  `sched_name` varchar(120) NOT NULL,
  `trigger_name` varchar(200) NOT NULL,
  `trigger_group` varchar(200) NOT NULL,
  `job_name` varchar(200) NOT NULL,
  `job_group` varchar(200) NOT NULL,
  `description` varchar(250) DEFAULT NULL,
  `next_fire_time` bigint(20) DEFAULT NULL,
  `prev_fire_time` bigint(20) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `trigger_state` varchar(16) NOT NULL,
  `trigger_type` varchar(8) NOT NULL,
  `start_time` bigint(20) NOT NULL,
  `end_time` bigint(20) DEFAULT NULL,
  `calendar_name` varchar(200) DEFAULT NULL,
  `misfire_instr` smallint(6) DEFAULT NULL,
  `job_data` blob DEFAULT NULL,
  PRIMARY KEY (`sched_name`,`trigger_name`,`trigger_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rep_demo_dxtj` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `gtime` datetime DEFAULT NULL COMMENT '雇佣日期',
  `update_by` varchar(50) DEFAULT NULL COMMENT '职务',
  `jphone` varchar(125) DEFAULT NULL COMMENT '家庭电话',
  `birth` datetime DEFAULT NULL COMMENT '出生日期',
  `hukou` varchar(32) DEFAULT NULL COMMENT '户口所在地',
  `laddress` varchar(125) DEFAULT NULL COMMENT '联系地址',
  `jperson` varchar(32) DEFAULT NULL COMMENT '紧急联系人',
  `sex` varchar(32) DEFAULT NULL COMMENT 'xingbie',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rep_demo_employee` (
  `id` varchar(10) NOT NULL COMMENT '主键',
  `num` varchar(50) DEFAULT NULL COMMENT '编号',
  `name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `sex` varchar(10) DEFAULT NULL COMMENT '性别',
  `birthday` datetime DEFAULT NULL COMMENT '出生日期',
  `nation` varchar(30) DEFAULT NULL COMMENT '民族',
  `political` varchar(30) DEFAULT NULL COMMENT '政治面貌',
  `native_place` varchar(30) DEFAULT NULL COMMENT '籍贯',
  `height` varchar(30) DEFAULT NULL COMMENT '身高',
  `weight` varchar(30) DEFAULT NULL COMMENT '体重',
  `health` varchar(30) DEFAULT NULL COMMENT '健康状况',
  `id_card` varchar(80) DEFAULT NULL COMMENT '身份证号',
  `education` varchar(30) DEFAULT NULL COMMENT '学历',
  `school` varchar(80) DEFAULT NULL COMMENT '毕业学校',
  `major` varchar(80) DEFAULT NULL COMMENT '专业',
  `address` varchar(100) DEFAULT NULL COMMENT '联系地址',
  `zip_code` varchar(30) DEFAULT NULL COMMENT '邮编',
  `email` varchar(30) DEFAULT NULL COMMENT 'Email',
  `phone` varchar(30) DEFAULT NULL COMMENT '手机�?,
  `foreign_language` varchar(30) DEFAULT NULL COMMENT '外语语种',
  `foreign_language_level` varchar(30) DEFAULT NULL COMMENT '外语水平',
  `computer_level` varchar(30) DEFAULT NULL COMMENT '计算机水�?,
  `graduation_time` datetime DEFAULT NULL COMMENT '毕业时间',
  `arrival_time` datetime DEFAULT NULL COMMENT '到职时间',
  `positional_titles` varchar(30) DEFAULT NULL COMMENT '职称',
  `education_experience` text DEFAULT NULL COMMENT '教育经历',
  `work_experience` text DEFAULT NULL COMMENT '工作经历',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建�?,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改�?,
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识0-正常,1-已删�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rep_demo_gongsi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gname` varchar(125) NOT NULL COMMENT '货品名称',
  `gdata` varchar(255) NOT NULL COMMENT '返利',
  `tdata` varchar(125) NOT NULL COMMENT '备注',
  `didian` varchar(255) NOT NULL,
  `zhaiyao` varchar(255) NOT NULL,
  `num` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rep_demo_jianpiao` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bnum` varchar(125) NOT NULL,
  `ftime` varchar(125) NOT NULL,
  `sfkong` varchar(125) NOT NULL,
  `kaishi` varchar(125) NOT NULL,
  `jieshu` varchar(125) NOT NULL,
  `hezairen` varchar(125) NOT NULL,
  `jpnum` varchar(125) NOT NULL,
  `shihelv` varchar(125) NOT NULL,
  `s_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rep_demo_xiaoshou` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hnum` varchar(125) NOT NULL COMMENT '货品编码',
  `hname` varchar(125) NOT NULL COMMENT '货品名称',
  `xinghao` varchar(125) NOT NULL COMMENT '单位',
  `fahuocangku` varchar(125) NOT NULL COMMENT '数量',
  `danwei` varchar(125) NOT NULL COMMENT '单价',
  `num` int(11) NOT NULL COMMENT '返利',
  `danjia` varchar(125) NOT NULL COMMENT '备注',
  `zhekoulv` int(11) NOT NULL,
  `xiaoshoujine` varchar(125) NOT NULL,
  `beizhu` varchar(125) DEFAULT NULL,
  `s_id` varchar(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `sys_config` (
  `config_id` bigint(20) NOT NULL,
  `config_name` varchar(100) NOT NULL,
  `config_key` varchar(100) NOT NULL,
  `config_value` varchar(500) DEFAULT NULL,
  `config_type` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`config_id`),
  UNIQUE KEY `uk_sys_config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_dept` (
  `dept_id` bigint(20) NOT NULL,
  `parent_id` bigint(20) NOT NULL DEFAULT 0,
  `dept_name` varchar(64) NOT NULL,
  `order_num` int(11) NOT NULL DEFAULT 0,
  `leader` varchar(64) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `status` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_dict_data` (
  `dict_code` bigint(20) NOT NULL,
  `dict_sort` int(11) NOT NULL DEFAULT 0,
  `dict_label` varchar(100) NOT NULL,
  `dict_value` varchar(100) NOT NULL,
  `dict_type` varchar(100) NOT NULL,
  `css_class` varchar(100) DEFAULT NULL,
  `list_class` varchar(100) DEFAULT NULL,
  `is_default` char(1) NOT NULL DEFAULT '0',
  `status` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`dict_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_dict_type` (
  `dict_id` bigint(20) NOT NULL,
  `dict_name` varchar(100) NOT NULL,
  `dict_type` varchar(100) NOT NULL,
  `status` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`dict_id`),
  UNIQUE KEY `uk_sys_dict_type` (`dict_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_job` (
  `job_id` bigint(20) NOT NULL,
  `job_name` varchar(64) NOT NULL,
  `job_group` varchar(64) NOT NULL DEFAULT 'DEFAULT',
  `invoke_target` varchar(500) NOT NULL,
  `cron_expression` varchar(255) NOT NULL,
  `misfire_policy` varchar(20) NOT NULL DEFAULT '3',
  `concurrent` char(1) NOT NULL DEFAULT '1',
  `status` char(1) NOT NULL DEFAULT '1',
  `params` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`job_id`),
  KEY `idx_sys_job_name` (`job_name`),
  KEY `idx_sys_job_group` (`job_group`),
  KEY `idx_sys_job_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_job_log` (
  `job_log_id` bigint(20) NOT NULL,
  `job_id` bigint(20) DEFAULT NULL,
  `job_name` varchar(64) NOT NULL,
  `job_group` varchar(64) NOT NULL,
  `invoke_target` varchar(500) NOT NULL,
  `job_message` varchar(500) DEFAULT NULL,
  `status` char(1) NOT NULL,
  `exception_info` varchar(2000) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`job_log_id`),
  KEY `idx_sys_job_log_create_time` (`create_time`),
  KEY `idx_sys_job_log_job_name` (`job_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_logininfor` (
  `info_id` bigint(20) NOT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `client_id` varchar(64) DEFAULT NULL,
  `ipaddr` varchar(128) DEFAULT NULL,
  `login_location` varchar(255) DEFAULT NULL,
  `browser` varchar(64) DEFAULT NULL,
  `os` varchar(64) DEFAULT NULL,
  `status` char(1) NOT NULL DEFAULT '0',
  `msg` varchar(500) DEFAULT NULL,
  `login_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_menu` (
  `menu_id` bigint(20) NOT NULL,
  `parent_id` bigint(20) NOT NULL DEFAULT 0,
  `menu_name` varchar(64) NOT NULL,
  `menu_type` char(1) NOT NULL,
  `path` varchar(200) DEFAULT NULL,
  `component` varchar(255) DEFAULT NULL,
  `route_name` varchar(64) DEFAULT NULL,
  `perms` varchar(500) DEFAULT NULL,
  `icon` varchar(64) DEFAULT NULL,
  `order_num` int(11) NOT NULL DEFAULT 0,
  `query` varchar(255) DEFAULT NULL,
  `is_frame` char(1) NOT NULL DEFAULT '0',
  `is_cache` char(1) NOT NULL DEFAULT '0',
  `visible` char(1) NOT NULL DEFAULT '0',
  `status` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_oauth_client` (
  `id` bigint(20) NOT NULL,
  `client_id` varchar(64) NOT NULL,
  `client_secret` varchar(256) NOT NULL,
  `client_name` varchar(128) DEFAULT NULL,
  `api_path_patterns` varchar(2000) DEFAULT NULL,
  `token_timeout` bigint(20) DEFAULT NULL,
  `check_captcha` char(1) NOT NULL DEFAULT '0',
  `status` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_oauth_client_client_id` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_oauth_user_bind` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) NOT NULL,
  `registration_id` varchar(64) NOT NULL,
  `external_subject` varchar(128) NOT NULL,
  `display_name` varchar(128) DEFAULT NULL,
  `avatar` varchar(512) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_oauth_bind` (`registration_id`,`external_subject`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_oper_log` (
  `oper_id` bigint(20) NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `business_type` int(11) NOT NULL DEFAULT 0,
  `method` varchar(200) DEFAULT NULL,
  `request_method` varchar(16) DEFAULT NULL,
  `operator_type` int(11) NOT NULL DEFAULT 0,
  `oper_name` varchar(64) DEFAULT NULL,
  `dept_name` varchar(64) DEFAULT NULL,
  `oper_url` varchar(500) DEFAULT NULL,
  `oper_ip` varchar(128) DEFAULT NULL,
  `oper_location` varchar(255) DEFAULT NULL,
  `oper_param` varchar(4000) DEFAULT NULL,
  `json_result` varchar(4000) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT 0,
  `error_msg` varchar(4000) DEFAULT NULL,
  `oper_time` timestamp NULL DEFAULT NULL,
  `cost_time` bigint(20) DEFAULT NULL,
  `trace_id` varchar(64) DEFAULT NULL,
  `client_operation_id` varchar(64) DEFAULT NULL,
  `client_id` varchar(64) DEFAULT NULL,
  `user_agent` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`oper_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_role` (
  `role_id` bigint(20) NOT NULL,
  `role_name` varchar(64) NOT NULL,
  `role_key` varchar(64) NOT NULL,
  `role_sort` int(11) NOT NULL DEFAULT 0,
  `data_scope` char(1) NOT NULL DEFAULT '1',
  `status` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE KEY `uk_sys_role_key` (`role_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_role_menu` (
  `role_id` bigint(20) NOT NULL,
  `menu_id` bigint(20) NOT NULL,
  PRIMARY KEY (`role_id`,`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_slow_sql` (
  `slow_id` bigint(20) NOT NULL,
  `sql_source` varchar(20) NOT NULL DEFAULT 'BUSINESS',
  `sql_type` varchar(20) NOT NULL DEFAULT 'OTHER',
  `mapper_id` varchar(500) NOT NULL DEFAULT '',
  `sql_text` text NOT NULL,
  `cost_time` bigint(20) NOT NULL DEFAULT 0,
  `trace_id` varchar(64) DEFAULT NULL,
  `client_operation_id` varchar(64) DEFAULT NULL,
  `client_id` varchar(64) DEFAULT NULL,
  `request_method` varchar(20) NOT NULL DEFAULT '',
  `request_uri` varchar(500) NOT NULL DEFAULT '',
  `oper_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`slow_id`),
  KEY `idx_sys_slow_sql_create_time` (`create_time`),
  KEY `idx_sys_slow_sql_trace_id` (`trace_id`),
  KEY `idx_sys_slow_sql_sql_source` (`sql_source`),
  KEY `idx_sys_slow_sql_sql_type` (`sql_type`),
  KEY `idx_sys_slow_sql_cost_time` (`cost_time`),
  KEY `idx_sys_slow_sql_client_operation_id` (`client_operation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_user` (
  `user_id` varchar(64) NOT NULL,
  `dept_id` bigint(20) DEFAULT NULL,
  `user_name` varchar(64) NOT NULL,
  `nick_name` varchar(64) DEFAULT NULL,
  `user_type` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `phonenumber` varchar(32) DEFAULT NULL,
  `sex` char(1) DEFAULT NULL,
  `password` varchar(200) NOT NULL,
  `status` char(1) NOT NULL DEFAULT '0',
  `del_flag` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uk_sys_user_name` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sys_user_role` (
  `user_id` varchar(64) NOT NULL,
  `role_id` bigint(20) NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `test_customer` (
  `id` int(32) NOT NULL AUTO_INCREMENT,
  `code` varchar(50) DEFAULT NULL COMMENT '客户编号',
  `name` varchar(50) DEFAULT NULL COMMENT '客户名称',
  `address` varchar(100) DEFAULT NULL COMMENT '客户地址',
  `yylx` varchar(2) DEFAULT NULL COMMENT '营业类型',
  `zyyw` varchar(255) DEFAULT NULL COMMENT '主营业务',
  `clsj` date DEFAULT NULL COMMENT '成立时间',
  `fzr` varchar(50) DEFAULT NULL COMMENT '负责�?,
  `phone` varchar(11) DEFAULT NULL COMMENT '手机�?,
  `khyj` varchar(255) DEFAULT NULL COMMENT '客户意见',
  `xypd` varchar(255) DEFAULT NULL COMMENT '信用评定',
  `tbr` varchar(50) DEFAULT NULL COMMENT '填表�?,
  `depts` varchar(50) DEFAULT NULL COMMENT '部门',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `test_monthly_report` (
  `id` varchar(50) NOT NULL COMMENT '主键',
  `by_sjfdl_yg` double DEFAULT NULL COMMENT '本月-实际发电�?有功',
  `lj_sjfdl_yg` double DEFAULT NULL COMMENT '累计-实际发电�?有功',
  `by_sjfdl_wg` double DEFAULT NULL COMMENT '本月-实际发电�?无功',
  `lj_sjfdl_wg` double DEFAULT NULL COMMENT '累计-实际发电�?无功',
  `by_khfdl` double DEFAULT NULL COMMENT '本月-考核发电�?,
  `lj_khfdl` double DEFAULT NULL COMMENT '累计-考核发电�?,
  `by_zdrfd` double DEFAULT NULL COMMENT '本月-最大日发电',
  `lj_zdrfd` double DEFAULT NULL COMMENT '累计-最大日发电',
  `by_ypjzdcl` double DEFAULT NULL COMMENT '本月-月平均最大出�?,
  `lj_ypjzdcl` double DEFAULT NULL COMMENT '累计-月平均最大出�?,
  `by_ypjzxcl` double DEFAULT NULL COMMENT '本月-月平均最小出�?,
  `lj_ypjzxcl` double DEFAULT NULL COMMENT '累计-月平均最小出�?,
  `by_qmzjrl` double DEFAULT NULL COMMENT '本月-期末装机容量',
  `lj_qmzjrl` double DEFAULT NULL COMMENT '累计-期末装机容量',
  `by_fdddjh` double DEFAULT NULL COMMENT '本月-发电调度计划',
  `lj_fdddjh` double DEFAULT NULL COMMENT '累计-发电调度计划',
  `by_jkzsl` double DEFAULT NULL COMMENT '本月-进库总水�?,
  `lj_jkzsl` double DEFAULT NULL COMMENT '累计-进库总水�?,
  `by_jyl` double DEFAULT NULL COMMENT '本月-降雨�?,
  `lj_jyl` double DEFAULT NULL COMMENT '累计-降雨�?,
  `by_zdjyl_zhi` double DEFAULT NULL COMMENT '本月-最大降雨量-�?,
  `lj_zdjyl_zhi` double DEFAULT NULL COMMENT '累计-最大降雨量-�?,
  `by_zdjyl_sj` double DEFAULT NULL COMMENT '本月-最大降雨量-时间',
  `lj_zdjyl_sj` double DEFAULT NULL COMMENT '累计-最大降雨量-时间',
  `by_zdrkll_zhi` double DEFAULT NULL COMMENT '本月-最大入库流�?�?,
  `lj_zdrkll_zhi` double DEFAULT NULL COMMENT '累计-最大入库流�?�?,
  `by_zdrkll_sj` double DEFAULT NULL COMMENT '本月-最大入库流�?时间',
  `lj_zdrkll_sj` double DEFAULT NULL COMMENT '累计-最大入库流�?时间',
  `by_zxrkll_zhi` double DEFAULT NULL COMMENT '本月-最小入库流�?�?,
  `lj_zxrkll_zhi` double DEFAULT NULL COMMENT '累计-最小入库流�?�?,
  `by_zxrkll_sj` double DEFAULT NULL COMMENT '本月-最小入库流�?时间',
  `lj_zxrkll_sj` double DEFAULT NULL COMMENT '累计-最小入库流�?时间',
  `by_jyts` double DEFAULT NULL COMMENT '本月-降雨天数',
  `lj_jyts` double DEFAULT NULL COMMENT '累计-降雨天数',
  `by_qsts` double DEFAULT NULL COMMENT '本月-弃水天数',
  `lj_qsts` double DEFAULT NULL COMMENT '累计-弃水天数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `test_order` (
  `id` varchar(32) NOT NULL,
  `order_name` varchar(50) DEFAULT NULL COMMENT '订单名称',
  `order_no` varchar(50) DEFAULT NULL COMMENT '订单编号',
  `order_sign_date` datetime DEFAULT NULL COMMENT '订单签订日期',
  `order_delivery_date` datetime DEFAULT NULL COMMENT '订单交付日期',
  `order_coms` varchar(50) DEFAULT NULL COMMENT '客户名称',
  `order_pers` varchar(50) DEFAULT NULL COMMENT '客户联系�?,
  `order_phone` varchar(15) DEFAULT NULL COMMENT '客户联系方式',
  `fzr` varchar(50) DEFAULT NULL COMMENT '负责�?,
  `depts` varchar(50) DEFAULT NULL COMMENT '负责人部�?,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `test_order_pros` (
  `id` varchar(32) NOT NULL,
  `pro_name` varchar(50) DEFAULT NULL COMMENT '产品名称',
  `pro_no` varchar(50) DEFAULT NULL COMMENT '产品编号',
  `pro_count` varchar(11) DEFAULT NULL COMMENT '产品数量',
  `pro_price` decimal(10,2) DEFAULT NULL COMMENT '产品单价',
  `pro_unit` varchar(10) DEFAULT NULL COMMENT '单位',
  `pro_model` varchar(10) DEFAULT NULL COMMENT '型号',
  `main_id` varchar(32) DEFAULT NULL COMMENT '外键',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `test_resume` (
  `id` int(32) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `sex` varchar(2) DEFAULT NULL COMMENT '性别',
  `birthday` date DEFAULT NULL COMMENT '出生日期',
  `phone` varchar(11) DEFAULT NULL COMMENT '手机�?,
  `email` varchar(50) DEFAULT NULL COMMENT '邮箱',
  `address` varchar(255) DEFAULT NULL COMMENT '现住址',
  `native_place` varchar(200) DEFAULT NULL COMMENT '籍贯',
  `nation` varchar(100) DEFAULT NULL COMMENT '民族',
  `political_outlook` varchar(50) DEFAULT NULL COMMENT '政治面貌',
  `education` varchar(10) DEFAULT NULL COMMENT '学历',
  `graduation_school` varchar(50) DEFAULT NULL COMMENT '毕业院校',
  `self_evaluation` varchar(255) DEFAULT NULL COMMENT '自我评价',
  `salary_expectation` decimal(10,2) DEFAULT NULL COMMENT '期望薪资',
  `edu_experience` varchar(255) DEFAULT NULL COMMENT '教育经历',
  `work_experience` varchar(255) DEFAULT NULL COMMENT '工作经历',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tmp_report_data_1` (
  `monty` varchar(255) DEFAULT NULL COMMENT '月份',
  `main_income` decimal(10,2) DEFAULT NULL,
  `total` decimal(10,2) DEFAULT NULL,
  `his_lowest` decimal(10,2) DEFAULT NULL,
  `his_average` decimal(10,2) DEFAULT NULL,
  `his_highest` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tmp_report_data_income` (
  `biz_income` varchar(100) DEFAULT NULL,
  `bx_jj_yongjin` decimal(10,2) DEFAULT NULL,
  `bx_zx_money` decimal(10,2) DEFAULT NULL,
  `chengbao_gz_money` decimal(10,2) DEFAULT NULL,
  `bx_gg_moeny` decimal(10,2) DEFAULT NULL,
  `tb_zx_money` decimal(10,2) DEFAULT NULL,
  `neikong_zx_money` decimal(10,2) DEFAULT NULL,
  `total` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
